spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0


  datasource:

    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:footballManager}
    username: ${DB_USER:footballManager}
    password: ${DB_PASSWORD:footballManager}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres